services:
  coupon-api:
    build: .
    container_name: outforce-coupon
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/swagger-ui.html"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s